/*
 * This file is part of Cleanflight and Betaflight.
 *
 * Cleanflight and Betaflight are free software. You can redistribute
 * this software and/or modify this software under the terms of the
 * GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * Cleanflight and Betaflight are distributed in the hope that they
 * will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software.
 *
 * If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include <stdint.h>

/* ------------------------------------------------------------------ *
 *  Compile-time limits (override before including if needed)          *
 * ------------------------------------------------------------------ */
/*
 * These defaults are deliberately smaller than the standalone library's
 * (20 x 15 x 10, ~117KB) — Betaflight itself already uses most of the
 * primary RAM region on typical F4 targets, so the full-size LUT does
 * not fit. Override before including this header if your target has
 * room to spare.
 */
#ifndef DRONE_DROP_MAX_ALT_LEVELS
#define DRONE_DROP_MAX_ALT_LEVELS    10
#endif
#ifndef DRONE_DROP_MAX_HSPEED_LEVELS
#define DRONE_DROP_MAX_HSPEED_LEVELS 8
#endif
#ifndef DRONE_DROP_MAX_VSPEED_LEVELS
#define DRONE_DROP_MAX_VSPEED_LEVELS 5
#endif

#define DRONE_DROP_MAX_COMBOS \
    (DRONE_DROP_MAX_ALT_LEVELS * DRONE_DROP_MAX_HSPEED_LEVELS * DRONE_DROP_MAX_VSPEED_LEVELS)

/* ------------------------------------------------------------------ *
 *  Status codes                                                        *
 * ------------------------------------------------------------------ */
typedef enum {
    DRONE_DROP_OK           =  0,
    DRONE_DROP_ERR_FILE     = -1,
    DRONE_DROP_ERR_FORMAT   = -2,
    DRONE_DROP_ERR_OVERFLOW = -3,
    DRONE_DROP_ERR_NO_DATA  = -4,
    DRONE_DROP_ERR_NOT_INIT = -5
} DroneDrop_Status;

/* ------------------------------------------------------------------ *
 *  Prediction output                                                   *
 *                                                                      *
 *  All offsets are in the drone's body frame at failure time:          *
 *    +X  = forward  (along horizontal velocity vector)                 *
 *    +Y  = right    (lateral, perpendicular to velocity)               *
 *                                                                      *
 *  To convert to world frame: rotate (mean_x_m, mean_y_m) by heading. *
 * ------------------------------------------------------------------ */
typedef struct {
    float mean_x_m;        /* Mean crash offset — forward direction   (m) */
    float mean_y_m;        /* Mean crash offset — lateral direction   (m) */
    float std_x_m;         /* Std dev — forward direction             (m) */
    float std_y_m;         /* Std dev — lateral direction             (m) */
    float mean_distance_m; /* Mean crash distance from failure point  (m) */
    float p95_distance_m;  /* 95th-percentile safety radius           (m) */
} DroneDrop_Prediction;

/* ------------------------------------------------------------------ *
 *  Public API                                                          *
 * ------------------------------------------------------------------ */

/*
 * Load the sweep CSV (from the SD card, via asyncfatfs) and build the
 * internal LUT. Call once at boot, after afatfs has reached
 * AFATFS_FILESYSTEM_STATE_READY and before the scheduler starts —
 * this call blocks (spin-polls afatfs) until the file is fully read.
 *
 * csv_path  – path to the CSV file generated by the simulator
 * returns     DRONE_DROP_OK on success, error code otherwise
 */
DroneDrop_Status drone_drop_init(const char *csv_path);

/*
 * Predict crash distribution for the flight state at the failure moment.
 * Inputs come directly from GPS / altitude estimator:
 *   altitude_m   – AGL altitude (m, must be > 0)
 *   h_speed_mps  – horizontal ground speed (m/s, >= 0)
 *   v_speed_mps  – vertical speed (m/s, positive = climbing)
 *
 * Pure computation — no I/O — safe to call from the flight loop.
 *
 * Returns DRONE_DROP_OK and fills *out on success.
 * Returns DRONE_DROP_ERR_NOT_INIT if drone_drop_init was not called.
 */
DroneDrop_Status drone_drop_predict(float altitude_m,
                                     float h_speed_mps,
                                     float v_speed_mps,
                                     DroneDrop_Prediction *out);

/*
 * Clear internal state. Safe to call even if init failed.
 */
void drone_drop_free(void);

/*
 * Number of LUT combo entries loaded. Returns 0 if not initialised.
 */
int drone_drop_lut_size(void);
